version: '3.11'

services:
  web:
    tty: true
    container_name: web
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    entrypoint: ./entrypoint.sh

  postgres:
    image: postgres:14-alpine3.17
    container_name: postgres
    hostname: postgres
    env_file:
      - ./.env
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - "25439:5432"

volumes:
  data-postgres: